/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import civitas.OperacionInmobiliaria;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author migue
 */
public class GestionarDialog extends javax.swing.JDialog {

    private int gestionElegida;
    
    /**
     * Creates new form GestionarDialog
     */
    public GestionarDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        DefaultListModel gestiones = new DefaultListModel<>(); // datos para la lista
        ArrayList<String> opciones = new ArrayList<> (Arrays.asList("Construir casa","Construir hotel","Terminar"));
        for (String s: opciones){
            gestiones.addElement(s);
        } //se completan los datos
        listaGestiones.setModel(gestiones); // se le dice  a la lista cuales son esos datos
        this.setVisible(true);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gestionesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaGestiones = new javax.swing.JList<>();
        realizarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        gestionesLabel.setText("Gestiones");
        getContentPane().add(gestionesLabel);

        listaGestiones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaGestiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaGestionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaGestiones);

        getContentPane().add(jScrollPane1);

        realizarBoton.setText("Realizar");
        realizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(realizarBoton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public OperacionInmobiliaria getGestionElegida() {
        switch (gestionElegida) {
            case 0:
                return OperacionInmobiliaria.CONSTRUIR_CASA;
            case 1:
                return OperacionInmobiliaria.CONSTRUIR_HOTEL;
            default:
                return OperacionInmobiliaria.TERMINAR;
        }

    }
    
    
    
    private void realizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarBotonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_realizarBotonActionPerformed

    private void listaGestionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaGestionesMouseClicked
        // TODO add your handling code here:
        gestionElegida = listaGestiones.getSelectedIndex(); 
        dispose();
    }//GEN-LAST:event_listaGestionesMouseClicked
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gestionesLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaGestiones;
    private javax.swing.JButton realizarBoton;
    // End of variables declaration//GEN-END:variables
}
