/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.CasillaCalle;
import civitas.Jugador;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JPanel;

/**
 *
 * @author migue
 */
public class JugadorPanel extends javax.swing.JPanel {

    private Jugador jugador;   
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }
    
    public JPanel getPropiedadesPanel() {
        return propiedadesPanel;
    }   

    public void setJugador(Jugador otro) {
    this.jugador = otro;
    nombreTextField.setText(this.jugador.getNombre());
    saldoTextField.setText(Float.toString(this.jugador.getSaldo()));
    if (this.jugador.getEspeculador()){
    especuladorTextField.setText("SI");
    }
    else{
    especuladorTextField.setText("NO");
    }
    
    rellenaPropiedades(this.jugador.getPropiedades());
    
    repaint();
    revalidate();
    }

    private void rellenaPropiedades(ArrayList<CasillaCalle> lista) {
        propiedadesPanel.removeAll();
        
        for(CasillaCalle t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        repaint();
        revalidate();
    }
    
    
    /*public void rellenaPropiedades(ArrayList<CasillaCalle> lista){
    propiedadesPanel.removeAll();
    for (int i = 0; i < lista.size(); i++) {
    CasillaCalle t = lista.get(i);
    PropiedadPanel vistaPropiedad = new PropiedadPanel();
    vistaPropiedad.setPropiedad(t);
    propiedadesPanel.add(vistaPropiedad);
    vistaPropiedad.setVisible(true);
    }
    repaint();
    revalidate();
    }
    */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        saldoLabel = new javax.swing.JLabel();
        saldoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        especuladorTextField = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        jPanel1.setMinimumSize(new java.awt.Dimension(338, 32));

        nombreLabel.setText("Nombre: ");
        jPanel1.add(nombreLabel);

        nombreTextField.setEditable(false);
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nombreTextField);

        saldoLabel.setText("Saldo: ");
        jPanel1.add(saldoLabel);

        saldoTextField.setEditable(false);
        jPanel1.add(saldoTextField);

        jLabel3.setText("Especulador: ");
        jPanel1.add(jLabel3);

        especuladorTextField.setEditable(false);
        jPanel1.add(especuladorTextField);

        add(jPanel1);

        propiedadesPanel.setForeground(new java.awt.Color(100, 100, 100));
        propiedadesPanel.setName(""); // NOI18N
        propiedadesPanel.setPreferredSize(new java.awt.Dimension(400, 200));
        propiedadesPanel.setLayout(new java.awt.BorderLayout());
        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add  handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField especuladorTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JTextField saldoTextField;
    // End of variables declaration//GEN-END:variables

}
