/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import civitas.CasillaCalle;
import javax.swing.JTextField;

/**
 *
 * @author migue
 */
public class PropiedadPanel extends javax.swing.JPanel {

    private CasillaCalle tituloPropiedad;
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }
    
    public void setPropiedad(CasillaCalle propiedad){
        this.tituloPropiedad = propiedad;
        this.nombreTextField.setText(this.tituloPropiedad.getNombre());
        this.numCasasTextField.setText(Integer.toString(this.tituloPropiedad.getNumCasas()));
        this.numHotelesTextField.setText(String.valueOf(this.tituloPropiedad.getNumHoteles()));
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        numCasasLabel = new javax.swing.JLabel();
        numCasasTextField = new javax.swing.JTextField();
        numHotelesLabel = new javax.swing.JLabel();
        numHotelesTextField = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(300, 32));
        setPreferredSize(new java.awt.Dimension(200, 32));

        nombreLabel.setText("Nombre propiedad: ");
        add(nombreLabel);

        nombreTextField.setEditable(false);
        add(nombreTextField);

        numCasasLabel.setText("Nº de casas: ");
        add(numCasasLabel);

        numCasasTextField.setEditable(false);
        numCasasTextField.setText("0");
        add(numCasasTextField);

        numHotelesLabel.setText("Nº de hoteles: ");
        add(numHotelesLabel);

        numHotelesTextField.setEditable(false);
        numHotelesTextField.setText("0");
        add(numHotelesTextField);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel numCasasLabel;
    private javax.swing.JTextField numCasasTextField;
    private javax.swing.JLabel numHotelesLabel;
    private javax.swing.JTextField numHotelesTextField;
    // End of variables declaration//GEN-END:variables

}
