/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package GUI;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import civitas.*;

/**
 *
 * @author migue
 */
public class PropiedadDialog extends javax.swing.JDialog {
    
    private int propiedadElegida;
    private CivitasJuego juego;
    private Jugador jugador;

    /** Creates new form PropiedadDialog */
    public PropiedadDialog(java.awt.Frame parent,boolean modal, Jugador otro) {
        super(parent, modal);
        initComponents();
        this.jugador=otro;
        this.propiedadElegida = -1;
        DefaultListModel propiedades = new DefaultListModel<>(); // datos para la lista
        ArrayList<String> opciones = new ArrayList<>();
        
        for (int i = 0; i < jugador.getPropiedades().size(); i++){
            opciones.add(jugador.getPropiedades().get(i).getNombre());
        }

        for (String s: opciones){
            propiedades.addElement(s);
        } //se completan los datos
        listaPropiedades.setModel(propiedades); // se le dice  a la lista cuales son esos datos
        this.setResizable(false);
        this.setVisible(true);
        
    }

    
    private void valorPropiedadesMouseClicked(java.awt.event.MouseEvent evt) {                                              
        propiedadElegida = listaPropiedades.getSelectedIndex();
        dispose();
    }

    public int getPropiedadElegida() {
        return propiedadElegida;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propiedadesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPropiedades = new javax.swing.JList<>();
        botonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        propiedadesLabel.setText("Propiedades");
        getContentPane().add(propiedadesLabel);

        listaPropiedades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPropiedades);

        getContentPane().add(jScrollPane1);

        botonOK.setText("OK");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });
        getContentPane().add(botonOK);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botonOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPropiedades;
    private javax.swing.JLabel propiedadesLabel;
    // End of variables declaration//GEN-END:variables

}
